### ISSUE TITLE
Contributing Guidelines

### ISSUE THREAD

**Issue by phillc73** [sboulema/BrewDB#1]
I was wondering if it's worth publishing a few contributing guidelines, to cover such things as the db architecture, but also specifically the format for data entry.

For example from the `Hops` table:

* Some entries have a country designation after them. What are the guidelines for using this? Should all new entries have a country designation? Should older entries be updates where possible? E.g. Fuggles (GB)

* What are the guidelines for completing the `Trade` field? How does that differ from the `Info` field?

Or for the `Malts` table, if two different maltsers have a product named exactly the same, e.g. Pale Malt, should they always be separate entries?

I appreciate it's a bit of effort to write something like this, but I think it would be helpful for new contributors, to insure data consistency and that pull requests are more likely accepted.

**Comment by sboulema** [comment]
There is now a CONTRIBUTING.md which should answer all your questions :D

**Comment by phillc73** [comment]
Looks good. I think this could end up as a super valuable knowledge base (although with a lot of work of course).
