### ISSUE TITLE
[Suggestion] Make Malt EBCmin and EBCmax Nullable

### ISSUE THREAD

**Issue by phillc73** [sboulema/BrewDB#16]
Currently the columns EBCmin and EBCmax are not nullable. This means that any grain or malt where an EBC entry is not available, cannot be added to the database.

For example, [all the cereals](https://crispmalt.com/our-malts/non-malted-cereals/) offered by Crisp - Torrified Wheat, Oats, Corn, Rice have no EBC values.

Nor does the special [floor malted Maris Otter](https://crispmalt.com/our-malts/floor/) grain.

Nor, generally, do the [distilling malts.](https://crispmalt.com/our-malts/distilling/) I guess it's a question of whether these should be fundamentally included in the database. My opinion is that they should for completeness.

@sboulema Could I ask you to make this change please? And at the same time check the integrity of the Malt table? [TablePlus](https://tableplus.com/) is the tool I'm using for updating and it is fine with things, but I checked in [sqlitebrowser](https://sqlitebrowser.org/) and it wants to throw some errors.

**Comment by sboulema** [comment]
Done!
