### ISSUE TITLE
[Data Source] YeastBot repository

### ISSUE THREAD

**Issue by phillc73** [sboulema/BrewDB#2]
The [YeastBot repository](https://github.com/as0bu/yeastbot) could be a good place to start expanding the yeast data in BrewDB. Actual CSV in the [data directory](https://github.com/as0bu/yeastbot/tree/master/yeastbot_app/data).

There's also a [Google Sheet called YeastBot](http://tinyurl.com/yeastbot), which is access by invitation only. Although the repository and the spreadsheet share the same name, I have no idea if it is the same data.

Edit: Also found a [different Google hosted spreadsheet](https://docs.google.com/spreadsheets/d/11AmEJtahA-VEbOgN_kJ0YJ6TTXQLNiJpXSmcWIrewAY/edit#gid=0), open access, with yeast, hops and malt information.

**Comment by sboulema** [comment]
https://github.com/sboulema/BrewDB/wiki/Yeast-Sources
