### ISSUE TITLE
[Suggestion] Add New Columns to Yeast Table

### ISSUE THREAD

**Issue by phillc73** [sboulema/BrewDB#3]
I'd like to propose adding the following columns to the `Yeast` table:

* Form: Dry or Liquid 
* Strain: saccharomyces cerevisiae or kveik or brettanomyces etc
* Flocculation: High, Medium or Low
* Styles: E.g. "Complex full bodies Porters, Stouts and Ales"

**Comment by sboulema** [comment]
Done!
