### ISSUE TITLE
[Data Source] Maltsters to Add

### ISSUE THREAD

**Issue by phillc73** [sboulema/BrewDB#4]
List of maltsters to add

- [ ] [Crisp](https://crispmalt.com/)
- [ ] [Simpsons](https://www.simpsonsmalt.co.uk/)
- [ ] [Bairds](http://www.bairds-malt.co.uk/)
- [ ] [Warminster](https://www.warminster-malt.co.uk/)
- [ ] [Viking](https://www.vikingmalt.com/)
- [ ] [Best](https://bestmalz.de/en/)
- [ ] [Avangard](https://www.avangard-malz.de/en/)
- [ ] [Rahr](http://rahrmaltingco.com/)
- [ ] [Malteurope](https://www.malteurop.com/en)
- [ ] [Bestmalz](https://bestmalz.de/en/)

Additional supplies added to the list as appropriate.

**Comment by sboulema** [comment]
https://github.com/sboulema/BrewDB/wiki/Malt-Sources
