### ISSUE TITLE
[Data Source] Additional Hops Varieties

### ISSUE THREAD

**Issue by phillc73** [sboulema/BrewDB#5]
Links to a few websites where I spotted some additional hops varieties not yet in the db

* [Hopslist](http://www.hopslist.com/hops/)
* [Hopsteiner](https://www.hopsteiner.com/variety-data-sheets/)

Where there is a discrepancy in data, for example difference alpha-acid ranges, data from Hopsteiner is being preferentially used. 

Hopslist generally provides Style information.

Both can provide Substitute information.

**Comment by sboulema** [comment]
Thanks!

Created a Wiki page to keep track of these helpful sources :)
