### ISSUE TITLE
[Suggestion] Additional Columns to Malt Table

### ISSUE THREAD

**Issue by phillc73** [sboulema/BrewDB#6]
I was thinking that there could be some additional useful columns added to the Malt table.

While EBC and Yield are already included, other useful information would be:

* Grain Type - Barely, Wheat, Oats, Rye etc. Maybe this is already covered in the `Name` field
* Row. Barley being the most common grain is either mainly 2-row (EU) or 6-row (US). Could be handled in a lookup table potentially.
* Moisture Content (a percentage)
* Diastatic Power in °WK (Windisch-Kolbach units)
* Total Protein (a percentage)
* Total Soluble Nitrogen (a percentage)
* Friability (a percentage)

[This article](https://www.probrewer.com/library/malt/understanding-malt-analysis-sheets/) has some background.

I would just hate to add a whole bunch of malts and then discover that a lot of useful information was missing and everything needs an update.

Also, I'm not clear from the description in the Contributing.md guide, but is the `Yield` field Extract Yield (% DBFG)?

**Comment by sboulema** [comment]
- Grain type: already in the name, but could be added as a lookup for easy filtering of the data
- Other fields: sounds good to add

I am an extract/partial mash brewer so slightly skipping on these gnarly details 😉 😝 

Yield is mostly taken from here: http://howtobrew.com/book/section-2/what-is-malted-grain/extraction-and-maximum-yield

**Comment by phillc73** [comment]
Thanks for the link. I've actually never come across that book before. It looks really useful.

I think if the database is to have the widest possible value, then the more information included, to cover all types of brewers, might be the best approach.

Much of the additional information suggested above is available in a decent malt report from the supplier. e.g. https://crispmalt.com/malts/finest-maris-otter-ale-malt/

If it's OK with you, I'll submit a PR with the following new fields in the Malt table:

* GrainType - with associated lookup table, which will include 2-row and 6-row Barley
* MaxMoisture
* DiastaticPower
* TotalNitrogen
* KolbachIndex (a measure of total soluble protein)

**Comment by sboulema** [comment]
Go for it!

**Comment by phillc73** [comment]
Complete and merged.

**Comment by phillc73** [comment]
I'd like to propose changing the `TotalNitrogen` column to `TotalProtein`.

As I've been getting into adding new malts, starting with those from Crisp, I've realised that Total Nitrogen is an IoB (Institute of Brewing) analysis method, whereas Total Protein is an EBC (European Brewing Convention) method of analysis.

Everything else we're adding; Kolbach Index, Diastatic Power in Windisch-Kolbach units and colour, is from the EBC methods. Therefore, Total Nitrogen is a bit of an anomaly and I think we should standardise everything on one method. I'm proposing EBC.

Edit: Or, Total Protein could be added as an additional field, and Total Nitrogen kept. However, then it's probably worth adding SNR (Soluble Nitrogen Ratio) from IoB as well, seeing as we have Kolbach Index from EBC.

**Comment by sboulema** [comment]
Adding SNR sounds good, more possible data equals a larger group that can use the database.

As long as the field can be NULL it should be fine and not prevent us from adding malts that only have EBC info.

**Comment by phillc73** [comment]
OK, so I'll add both a Total Protein and SNR field.
